- name: installing mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed
- name: enable mysql server and start
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started
- name: python libraries
  ansible.builtin.pip:
    name:  "{{item}}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: connect to mysql
  community.mysql.mysql_info:
    login_user: "{{mysql_user}}"
    login_password: "{{ lookup('amazon.aws.aws_ssm','/expense/mysql/mysql_root_password','decrypt=true') }}"
    login_host: "{{mysql_host}}"
  register: mysql_info
  ignore_errors: true
- name: print the results
  ansible.builtin.debug:
    msg: "{{mysql_info}}"
- name: sett root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
  when:  mysql_info.failed is true
